<?php
/**
 * GenZHype | VIDEO factory feed (read-only, fast). The external faceless-video maker (GitHub
 * Actions: edge-tts + FFmpeg) GETs this to get the next drama to turn into a 9:16 Short. Scripts
 * are PRE-GENERATED by the cron (video_factory.php) so this endpoint does NO AI work = never 504s.
 * The maker passes ?done=<comma page_ids it already rendered>; we return the newest not-yet-made
 * one that has a ready script. Token-gated. Site is read-only; the finished MP4 -> video_receive.php.
 *
 * GET ?token=...&done=12,44   ->   {"post": {...}} | {"post": null}
 */
declare(strict_types=1);
$APP = dirname(__DIR__, 2) . '/app';
$GLOBALS['CONFIG'] = require $APP . '/config.php';
require $APP . '/helpers.php';
require $APP . '/db.php';
require_once $APP . '/video_factory.php';
header('Content-Type: application/json');

// Accept params from a JSON POST body as well as GET. Hostinger's WAF intermittently
// 403s datacenter GETs but reliably passes JSON POSTs (the same channel that delivers
// the finished video every day) — so the maker fetches via POST to dodge the block.
$IN = $_GET;
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $body = json_decode((string)file_get_contents('php://input'), true);
    if (is_array($body)) $IN = $body + $_GET;
}

if (!hash_equals($CONFIG['ingest_token'] ?? '', (string)($IN['token'] ?? ''))) { http_response_code(403); echo json_encode(['error' => 'bad token']); exit; }

$pdo = db();
try { video_factory_install($pdo); } catch (Throwable $e) {}
$done = array_filter(array_map('intval', explode(',', (string)($IN['done'] ?? ''))));

// newest ready script whose page is still published+indexed and not already made
$rows = $pdo->query("SELECT v.page_id, v.slug, v.title, v.hook, v.script, v.image, v.broll, v.shotlist, v.gravity, v.force_render
                     FROM video_scripts v JOIN pages p ON p.id=v.page_id
                     WHERE p.status='published' AND p.robots='index'
                     ORDER BY (v.shotlist IS NOT NULL) DESC, (v.tpl >= 2) DESC, v.created_at DESC LIMIT 40")->fetchAll();
// directed scripts ALWAYS outrank undirected ones: a manual run must never burn a
// script in fallback mode while a fully-directed video sits waiting
$pick = null;
foreach ($rows as $r) { if (!in_array((int)$r['page_id'], $done, true)) { $pick = $r; break; } }
if (!$pick) { echo json_encode(['post' => null, 'reason' => 'nothing new']); exit; }

// VISUAL POOL for multi-scene cuts (real Reels change shots every few seconds):
// hero photo + event YouTube receipt thumbnails + the real people's names (the
// maker resolves their photos via Wikidata, image-engine style). v6: extraction
// lives in video_event_visuals() — the SAME function the Director uses to
// number its VISUALS list, so shot.visual_i = index into visuals[] here; the
// aligned visual_titles[] ride along for maker logging/debugging.
// (The tall branded TEXT card stays out of the pool — owner verdict on video
// #1: crop-zooming a text poster renders as unreadable letter fragments.)
$visuals = [$pick['image']];
$visualTitles = ['cover photo of the story'];
$meta = $pdo->prepare("SELECT d.id did, d.people_json, p.slug FROM dramas d JOIN pages p ON p.id=d.page_id WHERE p.id=?");
$meta->execute([(int)$pick['page_id']]);
$m = $meta->fetch();
$people = [];
if ($m) {
    [$visuals, $visualTitles] = video_event_visuals($pdo, (int)$m['did'], (string)$pick['image']);
    // v8: people as [{"name","photo"}] — faces resolved through the site's
    // arsenal (entity QID -> creator photo -> YouTube avatar), 30d-cached so
    // this stays fast in a web request; AI name extraction is cron-only and
    // this endpoint reads its cached result.
    try {
        require_once $APP . '/video_people.php';
        $people = video_people_resolve($pdo, (int)$pick['page_id'], (string)$m['people_json'],
                                       (string)$pick['title'], mb_substr((string)$pick['script'], 0, 200));
    } catch (Throwable $e) { $people = []; }
}

// v4.5 REAL-VISUALS: the receipt cards (one PNG per dated event, idx order —
// shotlist receipt shots reference these by receipt_i). v5: the same list also
// carries REAL-POST cards (authentic X screenshots, post_cards.php) appended
// after the event cards. v6: ONE branded PROMO card is appended LAST (kind
// order: events, posts, promo — final-CTA use only). Same idx space, so the
// feed shape is unchanged. Generation is pure Imagick/GD on real DB text (no
// AI, fast) and idempotent, so calling it here is safe; still wrapped so a
// render hiccup can never 504 the feed.
// r14 SIGHT FLAGS: the seeing pass (visual_sight.php, direction-time vision)
// already LOOKED at these images and cached what it saw. The per-image
// text_heavy/faces verdicts join the feed aligned with visuals[] so the maker
// can trust sight over its filename/aspect heuristic. Cache-read only (web
// never spends vision quota); images without a sighting ride as null.
$visualFlags = [];
try {
    require_once $APP . '/visual_sight.php';
    $sight = visual_sight_describe($pdo, $visuals);   // PHP_SAPI!=cli -> cache only
    foreach ($visuals as $u) {
        $visualFlags[] = isset($sight[$u])
            ? ['text_heavy' => !empty($sight[$u]['text_heavy']),
               'faces'      => (int)($sight[$u]['faces'] ?? 0)]
            : null;
    }
    if (!array_filter($visualFlags, fn($f) => $f !== null)) $visualFlags = [];
} catch (Throwable $e) { $visualFlags = []; }

$receipts = []; $receiptMeta = [];
try {
    require_once $APP . '/receipt_cards.php';
    foreach (receipt_cards_for_page($pdo, (int)$pick['page_id']) as $rc) {
        $receipts[] = $rc['url'];   // r17: '' at event positions (beige retired) — idx alignment holds
        $receiptMeta[] = ['kind' => (string)($rc['kind'] ?? 'event'),
                          'source_url' => (string)($rc['source_url'] ?? ''),    // v10
                          'og_image' => (string)($rc['og_image'] ?? '')];       // r17: report photo fallback
    }
} catch (Throwable $e) { $receipts = []; $receiptMeta = []; }

echo json_encode([
    'post' => [
        'page_id' => (int)$pick['page_id'],
        'slug'    => $pick['slug'],
        'title'   => $pick['title'],
        'hook'    => $pick['hook'],
        'script'  => $pick['script'],
        'image'   => $pick['image'],
        'visuals' => $visuals,                    // v6: video_event_visuals order (dedup built in)
        'visual_titles' => $visualTitles,         // v6: aligned with visuals[] (maker logging/debug)
        'visual_flags'  => $visualFlags,          // r14: aligned sight verdicts [{text_heavy,faces}|null] (empty = no sight yet)
        'people'  => array_slice($people, 0, 4),  // v8: [{"name","photo"}]; r11 +"photos":[urls] (maker keeps string compat)
        'broll'   => (array)json_decode((string)($pick['broll'] ?? ''), true) ?: [],
        'shotlist'=> json_decode((string)($pick['shotlist'] ?? ''), true) ?: null,   // v4 DIRECTOR EDL (word-anchored)
        'receipts'=> $receipts,   // v4.5: evidence-card PNGs in idx order (receipt_i -> receipts[i])
        'receipt_meta' => $receiptMeta,   // v10: [{kind, source_url}] aligned with receipts[]
        'gravity' => (string)($pick['gravity'] ?? 'standard'),   // r16: 'grave' = tragedy register (maker calms bgm/sfx/tts)
        'force'   => (bool)($pick['force_render'] ?? false),   // r19: requeued render — maker ignores its done-list
        'link'    => url('/drama/' . $pick['slug'] . '/'),
    ],
], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
